# Generated by Django 4.2.6 on 2023-10-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя доктора ')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия доктора ')),
                ('phone_num', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Номер телефона ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('exp', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Опыт работы ')),
                ('speciality', models.CharField(max_length=100, verbose_name='Название специальности   ')),
                ('photo', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
